### ISSUE TITLE
Improve syntax highlighting

### ISSUE THREAD

**Issue by Natrium729** [sideburns3000/vscode-dialog-language#7]
Some improvements that can be done on the syntax highlighting:

- Highlighting:
  - Rule declarations and queries (e.g. `(my rule)`) (as `entity.name.function`).
  - Current topic declaration (`#object` at the begining of a line) (as `markup.heading`, maybe?).
  - Dictionary words, including the ones without `@` in lists (as `string.quoted.other` or `string.unquoted`, maybe?), and the escaped characters they contain (as `constant.character.escape`).
  - `@` before access predicates (as `storage.modifier`, maybe?), and `*` before queries (as `keyword.control`, maybe?).
  - `(now)`, `(exhaust)` and others such as `(collect $)` (as `keyword.control`).
  - Escaped characters in prose such as `\$` (as `constant.character.escape`).
  - Numbers (as `constant.numeric`).
  - Anything else (as `invalid.illegal`).
- Removing the highlighting of double-quoted strings, since they don't mean anything special in Dialog.
- Fixing the comments: there's a typo in the regex, where it state `"^[%%].*$"`. That means a line starting with either a percentage or a percentage, which is pointless. The brackets should be removed so that only lines with 2 "%" are considered.
- Allowing extra spaces in keywords (`( if )` is valid, for instance).
- Changing the scopes of object identifiers and the current topic, because while they are highlighted in your screenshots, they are not in the default Dark/Dark+ theme. I suggest making object identifiers `constant.language` and the current topic asterisk `variable.language`, and change the scope of variables from `constant.language` to `variable.other`, since it fits Dialog semantics better: objects identifiers are constant (`#lamp` will always refer to `#lamp`), `*` is a special language variable referring to the current topic, and variables starting with `$` are just regular variables.

(Also, the scopes' names should end with `.dg` instead of `.dialog` since the main scope is `source.dg` and not `source.dialog`. And sometimes the suffix is missing, too.)

I've made all these changes (and more) on my machine. Here is an example showcasing some of them.

Before:

![dialog-syntax-before](https://user-images.githubusercontent.com/24978378/131601619-4a077f33-e20e-4705-bb76-f181135f608d.png)

After:

![dialog-syntax-after](https://user-images.githubusercontent.com/24978378/131601647-15af6b37-b506-4615-9d67-550d4dbc5a6a.png)

(Theme: Dark+)

On one hand, it's closer to Dialog semantics and it makes it easier to spot errors. (For example, the escaped "$" is not handled currently, and it makes it look like a variable.)

On the other hand:
- It can give the code a "Christmas tree" look, especially when the code has little prose (e.g. the standard library). But the same happens in other languages, like JavaScript.
- It makes the syntax definition way more complicated, with awful regexes in some parts.
- It might be a bit opinionated, and some scopes are debatable. Should the current topic be highlighted as a header? Are dictionary words really strings? What predicates are keywords? For the latter, I decided that what is listed under [special syntax](https://linusakesson.net/dialog/docs/quickref.html) (i.e. multi-part queries like `(if)(then)(else)`, queries that affect the next statement like `(exhaust)` or `(div $)`, or any special syntax like `(global variable (my global $))`) are keywords. That excludes `(stop)` and `(repeat forever)`, unlike this extension currently, as well as `(fail)`; I'm however tempted to consider them like keywords too. Moreover, formatting queries such as `(par)` or `(uppercase)` would be considered normal queries and highlighted as such, but I can see how it can be useful to highlight them differently, like the extension currently does.

Personnally, I globally prefer what I did over what the extension does right now. I'm still testing the changes in case there are rough edges left, then I can make a pull request if you accept them and are OK with the changes (else we can discuss them here). In any case, I think some changes have to be made, such as the comment bug fix, removing the quoted string highlighting, and changing the scope of the object identifiers. Also, correctly adding the `.dg` suffix to every scope.

**Comment by Natrium729** [comment]
In fact, some of the things I proposed might have been made already, according to this message on intfiction.org?

https://intfiction.org/t/dialog-syntax-highlighting-extension-for-visual-studio-code/42469/3

But it looks like this repository does not have those changes? Is there a reason?

**Comment by sideburns3000** [comment]
Hello, thanks for the report!

If I remember correctly, I had been planning to implement more features for the extension, and at that time considered whether to add some things in the "classic" (before LSP) way, or whether to try my hand at writing a language server.

But then I got sidetracked by other projects and seem to have forgotten to put in the smaller fixes, which should of course be possible independently of the larger plans.

Thanks again for the reminder and for the detailed suggestions!

I remember that it was quite difficult to choose the right token categories etc., because they should make reasonable sense regarding the semantics, and also should be widely supported by some of the major themes (and good looking).

At first glance, I think my local version does contain improvements over the published version in this repo, but your version is probably even better. I will look into the matter and will examine my local version, and report back.

**Comment by Natrium729** [comment]
> but your version is probably even better.

Well, I guess it's because I just love writing regular expressions? 😅

Since my work is done anyway, I can still make a pull request so that you can see and comment, even it's not merged in the end. I'll do it when I get some time.

Regarding what you did as described in the above intfiction.org post, I have a suggestion : don't use the string scope for the prose. It's such a big part of a Dialog source code, I find it distracting to have it in bright orange all the time. As an example, VS Code's built-in Markdown or HTML syntax highlighters does not hightlight the main text as a string.

I understand it was to disable the autocompletion pop-up, but maybe there's another way? (Anyway, I prefer having the autocompletion even for prose; it can allow faster typing.)

**Comment by Natrium729** [comment]
> […] or whether to try my hand at writing a language server.

A bit off-topic, but any news on that? Because that's actually a challenge that interests me too. So if writing a language server is not in your current priorities, and if you're OK with that, I may actually start working on one.

My language of choice would be Rust, because it's performant, well-suited for this kind of job, and I think it should be quite easy to integrate with extensions by compiling into WebAssembly (instead of having to compile an executable for each platform). Also I love Rust.

I just wanted to have some news, and I think I'll post a message about it on intfiction.org for more discussion. (And not to start something if someone is already working on a language server.)

**Comment by sideburns3000** [comment]
Thanks a lot for the PR, looking great!

About the language server:
> if you're OK with that, I may actually start working on one

Absolutely okay! :) 
I didn't get around to making a real attempt, and I'm involved in other projects at the moment, and for the near (or maybe even further) future, I'm not working on one, so I'm sure there'll be no risk of duplicating efforts.

Rust sounds good indeed, I'm looking forward to what you'll create. :+1:
